server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "system_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "varlogs"
          service: "AI_Trading_Bot"
          __path__: /var/log/*.log
  - job_name: "trading_bot"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "trading_bot"
          service: "TradingBot"
          __path__: /AI_Trading_Bot/logs/*.log
