global:
  scrape_interval: 15s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'ai_trading_bot'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Ajustar si se expone en otro puerto
